### PR TITLE
db_connector functions and config values

### PR DESCRIPTION
**Pull request by skaliak**

### CODE REVIEW

**Comment by LChristakis** [comment]
Peter, I've been having some trouble running the code for this branch to test it, because there's a mix of tabs and spaces for indentation. I'm going through and fixing it, but I just wanted to let you know in case I'm missing something.

**Comment by skaliak** [comment]
@LChristakis -- I think that's because I was using two different editors, and I guess one is set to use tabs and the other is set to use spaces.  Sorry about that!

**Comment by LChristakis** [comment]
No worries! Have you had any success testing this code? I was trying to run some manual tests and I had trouble with the MySQLdb connect function... I was also having some trouble with the unitttests code, but it's possible that the problem is because I'm using Windows.

**Comment by skaliak** [comment]
@LChristakis I haven't run the db_connector unittests with the new database info that we got from Kevin.  When I ran them on my own computer, I had MariaDB (a fork of MySQL) set up with a table named appointments with all the right fields.  The tests all passed in that environment.

You can either set up your own copy of the database, or run the tests on flip.  I haven't tried connecting to the "official" db server yet, and I think it probably doesn't have any tables defined yet.

Also, with the unittest.TestCase classes, some may be disabled with the @unittest.skip() decorator.  If you see a line like that, just comment it out.

**Comment by LChristakis** [comment]
Ok. The code looks good to me, I just wanted to test it before merging. I'll set up a MySQL db and get a connection set up.

On another note I'm having trouble setting up a free group in Podio. Does SlackHQ sound ok for a collaboration platform?

**Comment by skaliak** [comment]
That's fine, or we could just use the issue-tracking features in github (I forgot they were there).

**Comment by skaliak** [comment]
here is the table create code:
https://gist.github.com/skaliak/e94c526afb9facc8881a

**Comment by LChristakis** [comment]
Let's just stick to github then, it seems to be working well so far. Thanks for the table creation code; I'll run it on flip. Do you see any errors when you try to import the unittests.py code? I'm getting this error when I try to do so:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "unittests.py", line 49, in <module>
    class ParserTests(unittest.TestCase):
  File "unittests.py", line 53, in ParserTests
    Time: 1:00pm - 1:15pm"""
NameError: name 'self' is not defined

I feel like I'm missing something obvious, but I can't figure out how to get it to work...

**Comment by skaliak** [comment]
data (the multi-line string variable in ParserTests) used to be defined in __init__ but I moved it to the class level and I forgot to take off the "self.", and I guess I didn't run it again after that.  I'm going to fix it and push another commit to this branch.

**Comment by LChristakis** [comment]
Peter- sorry to keep pestering on this one branch, I've just been having some trouble testing it. I'm getting an error regarding the 'uuid' column in the appointment table I made using the table create code you provided. I wasn't sure what this column was for, could you help me out?

**Comment by skaliak** [comment]
Issue #11 is about the uuid.  It's necessary so outlook or gmail or whatever is receiving and processing the icalendar file is able to match up a cancellation with an appointment.  What error are you getting? -- Oh wait, I bet I know -- that column is set to NOT NULL in the db, so the create appointment function fails because it leaves that column out, right?

**Comment by LChristakis** [comment]
Yup, that's exactly the error I'm getting. I'll look into the UUID issue and modify unittests.py to include an appropriate UUID field in the database tests. Thanks for the tip.

**Comment by skaliak** [comment]
@LChristakis I'm amazed you're still awake.  It should be pretty obvious what needs to be changed in the SQL queries, but the row to dict function needs to look like this:
```python
def row_to_dict(row):
    fields = ['id', 'name', 'email', 'start', 'end', 'uid']
    d = dict(zip(fields, list(row)))
    d['uid'] = uuid.UUID(d['uid'])
    return d
```

Also, check out the new test file I added to this branch.

**Pull request merged**
