### PR TITLE
added query_appointments_by_week

### PR DESCRIPTION
**Pull request by skaliak**
I had already written this function, but I apparently I had it in a separate file that wasn't being tracked.

There's currently no test for it.

### CODE REVIEW

**Comment by LChristakis** [comment]
@skaliak Peter, is the week object defined anywhere? I'm looking at this line:

week_start = week.current_week_dates[0]

but I can't find any modules that match 'week'. Should I rewrite this to use datetime?

**Comment by skaliak** [comment]
Week is a WorkWeek object, which is defined in one of the other modules in this branch. Since an instance is passed and no new instances need to be created, it doesn't matter that this module doesn't import the workweek module (duck typing).

**Comment by skaliak** [comment]
@LChristakis @mhvoodoo Is this ok to merge?

**Comment by LChristakis** [comment]
@skaliak @mhvoodoo I'm not sure; I haven't been able to do any testing of it yet.

**Comment by LChristakis** [comment]
@skaliak @mhvoodoo Just finished testing and fixing bugs in db_connector.py and I think this branch is ready to be merged.

**Comment by skaliak** [comment]
@LChristakis Thanks!!

**Pull request merged**
