### PR TITLE
Peter procmail filter

### PR DESCRIPTION
**Pull request by skaliak**
#13

### CODE REVIEW

**Comment by skaliak** [comment]
@LChristakis @mhvoodoo this modified db_connector, so it should be merged before any work on #26 is started.

**Comment by LChristakis** [comment]
@skaliak @mhvoodoo shoot, just pushed a commit to fix #26 in this branch; please advise.

**Comment by skaliak** [comment]
@LChristakis if you applied the fix for #26 *in this branch* then it shouldn't be a problem.  Looks like this branch needs a manual merge anyway.

**Comment by skaliak** [comment]
@LChristakis Luke, can you do a manual merge of this branch, please?  You seem to have a knack for it...

**Comment by LChristakis** [comment]
@skaliak No problem, I'll take care of it.

**Comment by LChristakis** [comment]
@skaliak please advise. I'm resolving merge conflicts in `email_sender.py` and there's one particular line where I'm not sure which version of the file is correct. In the branch, line 67 has `server = smtplib.SMTP(config.smtp_server)` but in master on line 67 it says `server = smtplib.SMTP(config.smtp_server_ip)`- which of these is correct?

**Comment by skaliak** [comment]
@LChristakis the correct line is 
`server = smtplib.SMTP(config.smtp_server)`

**Pull request merged**
